### ISSUE TITLE
Liquibase support

### ISSUE THREAD

**Issue by likeanowl** [ml-in-programming/topias#13]
It would be better to keep all SQL-migrations in one place and use [liquibase](https://www.liquibase.org/) for auto-applying them

**Comment by sa160690** [comment]
Hi @likeanowl, can I take this up.

**Comment by likeanowl** [comment]
Hi @sa160690 !
Yes, feel free to take this issue! Unfortunately, this project lacks contributing guidelines and documentation yet, but I can answer your questions, if you have any. :)

**Comment by sa160690** [comment]
Can you please assign this to me.

**Comment by sa160690** [comment]
Do you already have sql scripts for the schema you intend to build?

**Comment by sa160690** [comment]
Hi @likeanowl, any update on this?

**Comment by likeanowl** [comment]
Hi @sa160690 !
Currently there is a lot of raw SQL in https://github.com/ml-in-programming/topias/blob/master/src/main/java/db/DatabaseInitialization.java . My main idea when creating this issue was to move all these initialization queries to liquibase patches.
If you have created some changes, please consider opening pull request, so I can review them and merge after.

**Comment by sa160690** [comment]
@likeanowl, I have raised a pull request: https://github.com/ml-in-programming/topias/pull/15

I still have not been able to test my changes. If possible, if you can guide me on how to test this plugin locally and I will be happy to do it. Thanks.

**Comment by likeanowl** [comment]
@sa160690 
Your PR looks good to me! Thank you!
To test it, you can run `runIde` task in gradle and check if anything good. Unfortunately, there is no any test coverage yet (but I plan to add some tests in close future). Therefore I usually test all changes manually.

**Comment by likeanowl** [comment]
Resolved in https://github.com/ml-in-programming/topias/pull/15
