### ISSUE TITLE
Create contribution guidelines

### ISSUE THREAD

**Issue by likeanowl** [ml-in-programming/topias#19]
Currently there is no any contribution guidelines. I think adding it may be helpful for newcomers.

**Comment by Evalle** [comment]
I can take care of it

**Comment by likeanowl** [comment]
Hi @Evalle !
It would be great, I'll assign this task to you. 👍

**Comment by likeanowl** [comment]
Resolved in https://github.com/ml-in-programming/topias/pull/22
